import { useState, useEffect } from "react";
import Head from "next/head";
import AppLayout from "../components/AppLayout";
import Button from "../components/Button";
import GitHub from "../components/Icons/GitHub";
import { colors } from "../styles/theme";

import { loginWithGitHub, onAuthStateChanged } from "../firebase/client";

export default function Home() {
  const [user, setUser] = useState(undefined);

  const handleClick = () => {
    loginWithGitHub()
      .then((user) => {
        setUser(user);
        console.log(user);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  useEffect(() => {
    // mantenie la sesion, cuando se refresca la pagina
    // onAuthStateChanged((user) => setUser(user));
    onAuthStateChanged(setUser);
  }, []);

  console.log("NNNN", user);

  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/devter-logo.png" alt="logo" />
          <h1>Devter</h1>
          <h2>
            Talk about development <br />
            with developers
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill={"#fff"} width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user && user.avatar && (
              <div>
                <img src={user.avatar} alt="logo" />
                <strong>{user.username}</strong>
              </div>
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>
        {`
          section {
            display: grid;
            height: 100%;
            place-content: center;
            place-items: center;
          }

          div {
            margin-top: 16px
          }

          img {
            width: 120px;
          }

          h1 {
            color: ${colors.secondary};
            font-weight: 800;
            margin-bottom: 16px;
          }

          h2 {
            color: ${colors.primary}
            font-size: 21px;
            margin: 0
          }
        `}
      </style>
    </>
  );
}
